### ISSUE TITLE
Summon round wooden tables for startup poker and family dinner

### ISSUE THREAD

**Issue by cryptogoth** [invisible-college/arcology-website#12]
Waiting on these
https://jerseyshore.craigslist.org/fuo/d/great-4th-of-july-rustic/6623868558.html

We could also scout out local electrical supply companies.

**Comment by varungpta** [comment]
https://newyork.craigslist.org/brk/fuo/d/outdoor-table-and-chairs/6704561031.html

**Comment by cryptogoth** [comment]
it's too cold now for winter rooftop events. we'll try again in the spring.
