### ISSUE TITLE
Create and follow up on maintenance tickets for toilet seats

### ISSUE THREAD

**Issue by cryptogoth** [invisible-college/arcology-website#16]
they don't fit for any of the toilets, and the one upstairs is sliding loose.

Log into property management company website using login info in #captains and create a maintenance ticket, follow up with them, and close it out when done.
Coordinate with @Down2nap who can be in the space during weekdays.

**Comment by casay** [comment]
commenting

**Comment by casay** [comment]
created ticket. 
https://topquality.managego.com/Resident/#/Ticket?sortExp=Modified&sortDir=desc&id=216298

**Comment by casay** [comment]
just checked, no response yet.

**Comment by casay** [comment]
he responded asking when is good for them to come by and fix it.
