### ISSUE TITLE
Get Arcology website to show up at a static Github site URL

### ISSUE THREAD

**Issue by cryptogoth** [invisible-college/arcology-website#21]
# Pros and Cons

The benefits to static page hosting at Github are:
* Automatic HTTPS support for privacy and authentication
* Easier deployment (automated jekyll builds or something?) after every commit, instead of the current flow which crons a pull every minute
* Separation of code from dynamic state, or we can statically generate all site content like https://linse.me/2016/09/13/Make-as-a-static-site-generator.html
* It's free! Unlike AWS or GCP or Digital Ocean.

Some downsides are
* We have to configure http://arcology.nyc to point to Github, which may cost money as a custom domain
* Slower, we can't scale up to more users (not currently a problem)

# Testing

It seems like testing with a static site would be easier, because you don't have to start a Node app, you just open an `index.html` file in a browser. However, some JS scripts will want to load things from an absolute `/something/something.js` path, and this doesn't work with the `file:///` scheme.

Options? We'll put this off until it becomes a problem.

# The task

Get the current page to show up at
http://arcology-website.github.io or some similar URL.

Here’s the documentation: https://help.github.com/articles/user-organization-and-project-pages/

It is currently a node app, but all the content is static in the `public` directory, and pulls its state from other source over the web.

**Comment by mishingo** [comment]
Currently just needs to be pointed to the gh-pages branch in the settings and the site will be live on: arcology-website.github.io

**Comment by cryptogoth** [comment]
i think other people have permission to make this change. i'm not clear what needs to be done, putting on back burner and we'll continue using node for now
