### ISSUE TITLE
Create an Airbnb listing for 10U

### ISSUE THREAD

**Issue by cryptogoth** [invisible-college/arcology-website#30]
use example photos from 8U for now, and copy listing description.
In photos, note that these are not photos of the exact bed,
and that it is a minimalist private room.

Update once photos are taken (separate issue) and room is built.

Block off days Oct 14 to Nov 1st.

**Comment by Down2nap** [comment]
I’d like to take this task on for certain. I will try and get it done by tomorrow evening.

**Comment by casay** [comment]
sorry, Adriana just seeing your comment after having started the listing, didnt mean to take over. I actually found it very helpful to go through the process of listing and reading all the things airbnb wrote about the process. It still needs a look over and pricing. probably more photos as well.

**Comment by cryptogoth** [comment]
This listing is completed and has been offered to Miranda, and she accepted.
Thanks all. I'll take care of prepping the room and add it to the work notes, since it's currently my room.
