### ISSUE TITLE
Prepare for community mealprep (10/18)

### ISSUE THREAD

**Issue by learner-long-life** [invisible-college/arcology-website#49]
Thursday, 10/17, 8pm -10pm
Message all Airbnb guests using a saved message.
```
Next Thursday we have a community mealprep at 8pm, and you're invited to come hang out with your housemates. We'll buy the ingredients and cook together a big stew, then split the cost and divide up the leftovers which you can eat for the next few days. It's nutritious, fun, and cheap. Let us know if you'd like to come.
```

Create a google calendar appointment similar to the previous one, inviting the same people:
https://www.google.com/calendar/event?eid=NDJiOWUyc3ZzZzFzYWszbmZvcTY4aXZoN3Qgb2NvZWJtZ2R1ZjBxbG1oZzI5aDU4ZXQ5N2tAZw

Keep a schedule in https://github.com/invisible-college/arcology-private/wiki/MealPrep
along with a record of who has paid their share of the ingredients.

Post a sign in the entry way bulletin board, or ask someone in the house to make one.

Ask Sergio to tell you when the next mealprep after this will be.
Close this ticket when you've created a new ticket, using this one as a template, for the following week.

**Comment by cryptogoth** [comment]
Yes, you're right, the 18th. Thanks for doing this, it's key to keeping
mealprep alive.

**Comment by kathara-jane** [comment]
hiii!
